import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {authPage} from '../utils/authPage'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<div>
  <h1>hello mane im here</h1>
</div>
 
    </div>
  )
}



// export async function getServerSideProps(ctx) {
//   const { token } = await authPage(ctx);
//    console.log('token in Server side in Dashboard',token);

//   return {
//     props: {
//       token,
//     },
//   };
// }
